// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eventSchemaHandler

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JoinClubPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinClubPayload(buf []byte, offset flatbuffers.UOffsetT) *JoinClubPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinClubPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishJoinClubPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJoinClubPayload(buf []byte, offset flatbuffers.UOffsetT) *JoinClubPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JoinClubPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJoinClubPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JoinClubPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinClubPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinClubPayload) ClubId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func JoinClubPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func JoinClubPayloadAddClubId(builder *flatbuffers.Builder, clubId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(clubId), 0)
}
func JoinClubPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
