// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eventSchemaHandler

import "strconv"

type Payload byte

const (
	PayloadNONE               Payload = 0
	PayloadJoinClubPayload    Payload = 1
	PayloadSendMessagePayload Payload = 2
	PayloadExitClubPayload    Payload = 3
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:               "NONE",
	PayloadJoinClubPayload:    "JoinClubPayload",
	PayloadSendMessagePayload: "SendMessagePayload",
	PayloadExitClubPayload:    "ExitClubPayload",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":               PayloadNONE,
	"JoinClubPayload":    PayloadJoinClubPayload,
	"SendMessagePayload": PayloadSendMessagePayload,
	"ExitClubPayload":    PayloadExitClubPayload,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
