// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package eventSchemaHandler

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SendMessagePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsSendMessagePayload(buf []byte, offset flatbuffers.UOffsetT) *SendMessagePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SendMessagePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishSendMessagePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSendMessagePayload(buf []byte, offset flatbuffers.UOffsetT) *SendMessagePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SendMessagePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSendMessagePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SendMessagePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SendMessagePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SendMessagePayload) Msg() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SendMessagePayload) MsgType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SendMessagePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SendMessagePayloadAddMsg(builder *flatbuffers.Builder, msg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(msg), 0)
}
func SendMessagePayloadAddMsgType(builder *flatbuffers.Builder, msgType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(msgType), 0)
}
func SendMessagePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
